[workspace]
members = ["db", "cli", "entity", "migration"]
resolver = "2"

[workspace.dependencies]
assert_cmd = "2.0.13"
async-std = "1"
clap = "4.5.1"
log = "0.4.19"
sea-orm = "0.12"
sea-orm-migration = "0.12.0"
tokio = "1"
