[package]
name = "entity"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
sea-orm = { workspace = true, features = [
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }

serde = { workspace = true }
serde_json = { workspace = true }