[package]
name = "common"
version = "0.0.1"
edition = "2021"

[dependencies]
dotenvy = { workspace = true }
env_logger = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }

[dev-dependencies]
temp-env = { workspace = true }