[package]
name = "api"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
lazy_static = { workspace = true }
serde_json = { workspace = true }