name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --check
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::unwrap_used -D clippy::expect_used
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: |
          cargo llvm-cov test
